# permissions for end users to view workloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workload-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: platform-operator
    app.kubernetes.io/part-of: platform-operator
    app.kubernetes.io/managed-by: kustomize
  name: workload-viewer-role
rules:
- apiGroups:
  - platform.mydev.org
  resources:
  - workloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.mydev.org
  resources:
  - workloads/status
  verbs:
  - get
